### ISSUE TITLE
Example knex API migration function to migrate a raw SQL file.  

### ISSUE THREAD

**Issue by bemorr** [ozum/knex-migrate-sql-file#2]
Hey Ozum -  would you consider adding an example of how an knex API `latest` migration function would look utilising your lib?
TIA

**Comment by ozum** [comment]
Hi @bemorr, if I didn't misunderstand the question, you should use `knex.migrate.latest()` as before. This library only provides `exports.up` and `exports.down` from SQL files, nothing more.

**Comment by bemorr** [comment]
hmm .... I thought that might be the case. Then my function is failing for another reason 🤨.

Can I confirm also that the 20200490984_migration.js file needs to be only :

```
module.exports = require("knex-migrate-sql-file")();
exports.up = function(knex) {};
exports.down = function(knex) {};
```
\+

The appended `.up.sql` &  `.down.sql` with the raw SQL?

**Comment by ozum** [comment]
Please delete `exports.up` and `exports.down` lines and try again:

```js
module.exports = require("knex-migrate-sql-file")();
// exports.up = function(knex) {};
// exports.down = function(knex) {};
```

**Comment by bemorr** [comment]
Great - that solves it. Thanks. I appreciate the prompt response 🍻
